name: Docker Image Build

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fxhash/fxhash-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  update-chart:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: fxhash/god
          ssh-key: ${{ secrets.MONOREPO_SSH_KEY }}
      - name: "Update Helm Chart values"
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          sed -i -e "s/tag:\(.*\)/tag: $GITHUB_SHA/g" charts/dependency-charts/fxh-api/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts/dependency-charts/fxh-api/values.yaml
          git commit -m "🤖 Github Actions: Update fxhash-api image version"
          git push
